name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION  }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy Application
        run: |
          aws deploy create-deployment \
            --application-name enigma \
            --deployment-group-name enigma-deploy \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --region ${{ secrets.AWS_REGION  }} \
            --file-exists-behavior OVERWRITE
