name: Deploy Enigma Casino

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      zip-name: enigma-backend.zip
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish backend
        working-directory: backend/the-enigma-casino-server
        run: |
          dotnet restore
          dotnet publish -c Release -o ../../deploy/backend/publish

      - name: Crear ZIP para CodeDeploy
        working-directory: deploy/backend
        run: |
          cp scripts/install.sh .
          cp scripts/start.sh .
          cp scripts/stop.sh .
          zip -r ../../enigma-backend.zip appspec.yml install.sh start.sh stop.sh publish/

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Subir artefacto a S3
        run: |
          aws s3 cp enigma-backend.zip s3://enigma-deployments/enigma-backend.zip

  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    env:
      CD_APP_NAME: "enigma-backend"
      CD_GROUP_NAME: "BackendGroup"
      IAM_ROLE: ${{ secrets.IAM_ROLE }}
      EC2_TAG_KEY: "Name"
      EC2_TAG_VALUE: "backend-instance"
    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Crear aplicación CodeDeploy (si no existe)
        run: |
          aws deploy get-application --application-name $CD_APP_NAME || \
          aws deploy create-application \
            --application-name $CD_APP_NAME \
            --compute-platform "Server"

      - name: Crear grupo de despliegue (si no existe)
        run: |
          aws deploy get-deployment-group \
            --application-name $CD_APP_NAME \
            --deployment-group-name $CD_GROUP_NAME || \
          aws deploy create-deployment-group \
            --application-name $CD_APP_NAME \
            --deployment-group-name $CD_GROUP_NAME \
            --service-role-arn $IAM_ROLE \
            --deployment-style deploymentType="IN_PLACE",deploymentOption="WITHOUT_TRAFFIC_CONTROL" \
            --ec2-tag-filters Key=$EC2_TAG_KEY,Value=$EC2_TAG_VALUE,Type=KEY_AND_VALUE

      - name: Lanzar despliegue CodeDeploy (backend)
        run: |
          aws deploy create-deployment \
            --application-name $CD_APP_NAME \
            --deployment-group-name $CD_GROUP_NAME \
            --s3-location bucket=enigma-deployments,key=enigma-backend.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --description "Despliegue backend desde GitHub" \
            --region ${{ secrets.AWS_REGION }}


  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      zip-name1: enigma-frontend1.zip
      zip-name2: enigma-frontend2.zip
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generar .env.production para frontend 1
        working-directory: frontend/the-enigma-casino-client
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production
          echo "VITE_WS_BASE_URL=${{ secrets.VITE_WS_BASE_URL }}" >> .env.production
          echo "VITE_STRIPE_PUBLIC_KEY=${{ secrets.VITE_STRIPE_PUBLIC_KEY }}" >> .env.production
          echo "VITE_DEPLOY_ENV=aws-frontend-1" >> .env.production

      - name: Build frontend 1
        working-directory: frontend/the-enigma-casino-client
        run: |
          npm install
          npm run build
          mv dist ../../dist1

      - name: Preparar ZIP Frontend 1
        run: |
          cp deploy/frontend/appspec.yml frontend/the-enigma-casino-client/
          cp deploy/frontend/scripts/*.sh frontend/the-enigma-casino-client/
          mv frontend/dist1 frontend/the-enigma-casino-client/dist
          cd frontend/the-enigma-casino-client
          zip -r ../../../enigma-frontend1.zip appspec.yml install.sh start.sh stop.sh dist/


      - name: Guardar build y regenerar .env.production para frontend 2
        working-directory: frontend/the-enigma-casino-client
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production
          echo "VITE_WS_BASE_URL=${{ secrets.VITE_WS_BASE_URL }}" >> .env.production
          echo "VITE_STRIPE_PUBLIC_KEY=${{ secrets.VITE_STRIPE_PUBLIC_KEY }}" >> .env.production
          echo "VITE_DEPLOY_ENV=aws-frontend-2" >> .env.production

      - name: Build frontend 2
        working-directory: frontend/the-enigma-casino-client
        run: |
          npm run build
          mv dist ../../dist1

      - name: Preparar ZIP Frontend 2
        run: |
          cp deploy/frontend/appspec.yml frontend/the-enigma-casino-client/
          cp deploy/frontend/scripts/install.sh frontend/the-enigma-casino-client/
          cp deploy/frontend/scripts/start.sh frontend/the-enigma-casino-client/
          cp deploy/frontend/scripts/stop.sh frontend/the-enigma-casino-client/
          cd frontend/the-enigma-casino-client
          zip -r ../../../enigma-frontend2.zip appspec.yml install.sh start.sh stop.sh dist/


      - name: Subir ZIP Frontend 1 a S3
        run: |
          aws s3 cp enigma-frontend1.zip s3://enigma-deployments/enigma-frontend1.zip

      - name: Subir ZIP Frontend 2 a S3
        run: |
          aws s3 cp enigma-frontend2.zip s3://enigma-deployments/enigma-frontend2.zip

  deploy-frontend1:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Lanzar despliegue CodeDeploy (frontend 1)
        run: |
          aws deploy create-deployment \
            --application-name enigma-frontend-1 \
            --deployment-group-name FrontendGroup1 \
            --s3-location bucket=enigma-deployments,key=enigma-frontend1.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --description "Despliegue frontend 1" \
            --region ${{ secrets.AWS_REGION }}

  deploy-frontend2:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Lanzar despliegue CodeDeploy (frontend 2)
        run: |
          aws deploy create-deployment \
            --application-name enigma-frontend-2 \
            --deployment-group-name FrontendGroup2 \
            --s3-location bucket=enigma-deployments,key=enigma-frontend2.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --description "Despliegue frontend 2" \
            --region ${{ secrets.AWS_REGION }}
