name: Deploy Enigma Casino

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Setup Node.js (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend con Vite
        working-directory: frontend/the-enigma-casino-client
        run: |
          npm ci
          npm run build

      - name: Copiar build al paquete de despliegue
        run: |
          mkdir -p deploy/frontend/build
          cp -r frontend/the-enigma-casino-client/dist/* deploy/frontend/build/

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restaurar dependencias backend
        working-directory: backend/the-enigma-casino-server
        run: dotnet restore

      - name: Compilar y publicar backend
        working-directory: backend/the-enigma-casino-server
        run: dotnet publish -c Release -o ../../deploy/backend/publish

      - name: Confirmar contenido publicado
        run: ls -la deploy/backend/publish

      - name: Empaquetar frontend
        run: |
          cd deploy/frontend
          zip -r ../../frontend-deploy.zip ./*

      - name: Empaquetar backend
        run: |
          cd deploy/backend
          zip -r ../../backend-deploy.zip ./*

      - name: Subir artefactos a EC2 vía SFTP
        run: |
          echo "$EC2_PRIVATE_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

          # === BACKEND ===
          echo "Subiendo backend-deploy.zip a ${{ secrets.BACKEND_IP }}"
          scp -i ec2_key.pem -o StrictHostKeyChecking=no backend-deploy.zip user-deploy@${{ secrets.BACKEND_IP }}:/home/user-deploy/zips/

          # === FRONTEND 1 ===
          echo "Subiendo frontend-deploy.zip a ${{ secrets.FRONTEND_IP_1 }}"
          scp -i ec2_key.pem -o StrictHostKeyChecking=no frontend-deploy.zip user-deploy@${{ secrets.FRONTEND_IP_1 }}:/home/user-deploy/zips/

          # === FRONTEND 2 ===
          echo "Subiendo frontend-deploy.zip a ${{ secrets.FRONTEND_IP_2 }}"
          scp -i ec2_key.pem -o StrictHostKeyChecking=no frontend-deploy.zip user-deploy@${{ secrets.FRONTEND_IP_2 }}:/home/user-deploy/zips/
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Publicar artefactos para descarga manual
        uses: actions/upload-artifact@v4
        with:
          name: backend-deploy
          path: backend-deploy.zip

      - name: Publicar artefactos para descarga manual (frontend)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-deploy
          path: frontend-deploy.zip